name: CI/CD Little Neighbors

on:
  push:
    branches: [ "main", "feature/*" ]
  pull_request:
    branches: [ "main", "feature/*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean verify


  docker_build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: alexandracoder/little_neighbors_project:latest


  docker_test:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Pull Docker image
        run: docker pull alexandracoder/little_neighbors_project:latest

      - name: Run container for smoke tests
        run: |
          docker run -d --name little_neighbors_test -p 8081:8081 \
          -e SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/littleneighbors \
          -e SPRING_DATASOURCE_USERNAME=user \
          -e SPRING_DATASOURCE_PASSWORD=password \
          -e SPRING_PROFILES_ACTIVE=prod \
          alexandracoder/little_neighbors_project:latest
          
          # Espera a que arranque
          sleep 15
          
          # Test simple: verificar endpoint raíz
          curl -f http://localhost:8081/actuator/health

          # Detener y eliminar contenedor
          docker stop little_neighbors_test
          docker rm little_neighbors_test



