name: CI/CD Little Neighbors

on:
  push:
    branches: [ "main", "feature/after-project" ]
  pull_request:
    branches: [ "main", "feature/after-project" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: littleneighbors
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build & Run Tests (JaCoCo)
        run: mvn clean verify

      - name: Archive JaCoCo reports
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-reports
          path: target/site/jacoco

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: alexandracoder/little_neighbors_project:latest

      - name: Upload Docker image digest
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-digest
          path: digest.txt



